/*++

Copyright (C) 2020 ADSK

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.7.0-develop.

Abstract: This is an autogenerated C++-Header file in order to allow an easy
 use of RTTI

Interface version: 1.0.0

*/

#ifndef __RTTI_DYNAMICHEADER_CPPTYPES
#define __RTTI_DYNAMICHEADER_CPPTYPES

#include "rtti_types.hpp"



/*************************************************************************************************************************
 Class definition for Base
**************************************************************************************************************************/

/*************************************************************************************************************************
 Class definition for Animal
**************************************************************************************************************************/

/*************************************************************************************************************************
 Class definition for Mammal
**************************************************************************************************************************/

/*************************************************************************************************************************
 Class definition for Reptile
**************************************************************************************************************************/

/*************************************************************************************************************************
 Class definition for Giraffe
**************************************************************************************************************************/

/*************************************************************************************************************************
 Class definition for Tiger
**************************************************************************************************************************/

/**
* Roar like a tiger
*
* @param[in] pTiger - Tiger instance.
* @return error code or 0 (success)
*/
typedef RTTIResult (*PRTTITiger_RoarPtr) (RTTI_Tiger pTiger);

/*************************************************************************************************************************
 Class definition for Snake
**************************************************************************************************************************/

/*************************************************************************************************************************
 Class definition for Turtle
**************************************************************************************************************************/

/*************************************************************************************************************************
 Class definition for AnimalIterator
**************************************************************************************************************************/

/**
* Return next animal
*
* @param[in] pAnimalIterator - AnimalIterator instance.
* @param[out] pAnimal - 
* @return error code or 0 (success)
*/
typedef RTTIResult (*PRTTIAnimalIterator_GetNextAnimalPtr) (RTTI_AnimalIterator pAnimalIterator, RTTI_Animal * pAnimal);

/*************************************************************************************************************************
 Class definition for Zoo
**************************************************************************************************************************/

/**
* Return an iterator over all zoo animals
*
* @param[in] pZoo - Zoo instance.
* @param[out] pIterator - 
* @return error code or 0 (success)
*/
typedef RTTIResult (*PRTTIZoo_IteratorPtr) (RTTI_Zoo pZoo, RTTI_AnimalIterator * pIterator);

/*************************************************************************************************************************
 Global functions
**************************************************************************************************************************/

/**
* retrieves the binary version of this library.
*
* @param[out] pMajor - returns the major version of this library
* @param[out] pMinor - returns the minor version of this library
* @param[out] pMicro - returns the micro version of this library
* @return error code or 0 (success)
*/
typedef RTTIResult (*PRTTIGetVersionPtr) (RTTI_uint32 * pMajor, RTTI_uint32 * pMinor, RTTI_uint32 * pMicro);

/**
* Returns the last error recorded on this object
*
* @param[in] pInstance - Instance Handle
* @param[in] nErrorMessageBufferSize - size of the buffer (including trailing 0)
* @param[out] pErrorMessageNeededChars - will be filled with the count of the written bytes, or needed buffer size.
* @param[out] pErrorMessageBuffer -  buffer of Message of the last error, may be NULL
* @param[out] pHasError - Is there a last error to query
* @return error code or 0 (success)
*/
typedef RTTIResult (*PRTTIGetLastErrorPtr) (RTTI_Base pInstance, const RTTI_uint32 nErrorMessageBufferSize, RTTI_uint32* pErrorMessageNeededChars, char * pErrorMessageBuffer, bool * pHasError);

/**
* Releases shared ownership of an Instance
*
* @param[in] pInstance - Instance Handle
* @return error code or 0 (success)
*/
typedef RTTIResult (*PRTTIReleaseInstancePtr) (RTTI_Base pInstance);

/**
* Acquires shared ownership of an Instance
*
* @param[in] pInstance - Instance Handle
* @return error code or 0 (success)
*/
typedef RTTIResult (*PRTTIAcquireInstancePtr) (RTTI_Base pInstance);

/**
* Injects an imported component for usage within this component
*
* @param[in] pNameSpace - NameSpace of the injected component
* @param[in] pSymbolAddressMethod - Address of the SymbolAddressMethod of the injected component
* @return error code or 0 (success)
*/
typedef RTTIResult (*PRTTIInjectComponentPtr) (const char * pNameSpace, RTTI_pvoid pSymbolAddressMethod);

/**
* Returns the address of the SymbolLookupMethod
*
* @param[out] pSymbolLookupMethod - Address of the SymbolAddressMethod
* @return error code or 0 (success)
*/
typedef RTTIResult (*PRTTIGetSymbolLookupMethodPtr) (RTTI_pvoid * pSymbolLookupMethod);

/**
* Test whether an object implements a given interface
*
* @param[in] pObject - Instance Handle
* @param[in] pClassName - Class name of the interface to test
* @param[out] pImplementsInterface - Will be set to true if pInstance implements the interface, false otherwise
* @return error code or 0 (success)
*/
typedef RTTIResult (*PRTTIImplementsInterfacePtr) (RTTI_Base pObject, const char * pClassName, bool * pImplementsInterface);

/**
* Create a new zoo with animals
*
* @param[out] pInstance - 
* @return error code or 0 (success)
*/
typedef RTTIResult (*PRTTICreateZooPtr) (RTTI_Zoo * pInstance);

/*************************************************************************************************************************
 Function Table Structure
**************************************************************************************************************************/

typedef struct {
	void * m_LibraryHandle;
	PRTTITiger_RoarPtr m_Tiger_Roar;
	PRTTIAnimalIterator_GetNextAnimalPtr m_AnimalIterator_GetNextAnimal;
	PRTTIZoo_IteratorPtr m_Zoo_Iterator;
	PRTTIGetVersionPtr m_GetVersion;
	PRTTIGetLastErrorPtr m_GetLastError;
	PRTTIReleaseInstancePtr m_ReleaseInstance;
	PRTTIAcquireInstancePtr m_AcquireInstance;
	PRTTIInjectComponentPtr m_InjectComponent;
	PRTTIGetSymbolLookupMethodPtr m_GetSymbolLookupMethod;
	PRTTIImplementsInterfacePtr m_ImplementsInterface;
	PRTTICreateZooPtr m_CreateZoo;
} sRTTIDynamicWrapperTable;

#endif // __RTTI_DYNAMICHEADER_CPPTYPES

