/*++

Copyright (C) 2021 ADSK

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.7.0-develop.

Abstract: This is an autogenerated Java file in order to allow an easy
 use of RTTI

Interface version: 1.0.0

*/

package rtti;

import com.sun.jna.Memory;
import com.sun.jna.Pointer;

import java.util.Arrays;
import java.util.List;

public class TestStruct {

	public int X;

	public int Y;

	public static final int SIZE = 8;

	public void readFromPointer(Pointer p, long offset) {
		X = p.getInt(offset + 0);
		Y = p.getInt(offset + 4);
	}

	public void writeToPointer(Pointer p, long offset) {
		p.setInt(offset + 0, X);
		p.setInt(offset + 4, Y);
	}

}

