/*++

Copyright (C) 2021 ADSK

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.7.0-develop.

Abstract: This is an autogenerated Java file in order to allow an easy
 use of RTTI

Interface version: 1.0.0

*/

package rtti;

import com.sun.jna.Library;
import com.sun.jna.Memory;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import java.lang.ref.Cleaner;


import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;

public class Zoo extends Base {

	public Zoo(RTTIWrapper wrapper, RTTIHandle handle) {
		super(wrapper, handle);
	}

	/**
	 * Return an iterator over all zoo animals
	 *
	 * @return 
	 * @throws RTTIException
	 */
	public AnimalIterator iterator() throws RTTIException {
		RTTIHandle handleIterator = new RTTIHandle();
		mWrapper.checkError(this, mWrapper.rtti_zoo_iterator.invokeInt(new java.lang.Object[]{mHandle.Value(), handleIterator}));
		AnimalIterator iterator = null;
		if (handleIterator.Handle == Pointer.NULL) {
		  throw new RTTIException(RTTIException.RTTI_ERROR_INVALIDPARAM, "Iterator was a null pointer");
		}
		iterator = mWrapper.PolymorphicFactory(handleIterator, AnimalIterator.class);
		return iterator;
	}


}

