# Configuration file for Travis CI (https://travis-ci.org)
#
# It used as a status check for all PRs and
# to generate the build-status-icon in the main README.md-file.

language: go

go:
  - 1.11.x

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      osx_image: xcode7.2

before_script:
    - cd Build

script:
    - sh build.sh
