/*++

Copyright (C) 2018 PrimeDevelopers

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.3.2.

Abstract: This is an autogenerated C++ header file in order to allow easy
development of Prime Numbers Library. The implementer of Prime Numbers Library needs to
derive concrete classes from the abstract classes in this header.

Interface version: 1.2.0

*/


#ifndef __LIBPRIMES_CPPINTERFACES
#define __LIBPRIMES_CPPINTERFACES

#include <string>

#include "libprimes_types.h"

namespace LibPrimes {

/**
 Forward declarations of class interfaces
*/
class ILibPrimesCalculator;
class ILibPrimesFactorizationCalculator;
class ILibPrimesSieveCalculator;


/*************************************************************************************************************************
 Class ILibPrimesBaseClass 
**************************************************************************************************************************/

class ILibPrimesBaseClass {
public:
	virtual ~ILibPrimesBaseClass () {}
};


/*************************************************************************************************************************
 Class interface for LibPrimesCalculator 
**************************************************************************************************************************/

class ILibPrimesCalculator : public virtual ILibPrimesBaseClass {
public:
	/**
	* ICalculator::GetValue - Returns the current value of this Calculator
	* @return The current value of this Calculator
	*/
	virtual LibPrimes_uint64 GetValue () = 0;

	/**
	* ICalculator::SetValue - Sets the value to be factorized
	* @param[in] nValue - The value to be factorized
	*/
	virtual void SetValue (const LibPrimes_uint64 nValue) = 0;

	/**
	* ICalculator::Calculate - Performs the specific calculation of this Calculator
	*/
	virtual void Calculate () = 0;

	/**
	* ICalculator::SetProgressCallback - Sets the progress callback function
	* @param[in] pProgressCallback - callback function
	*/
	virtual void SetProgressCallback (const LibPrimesProgressCallback pProgressCallback) = 0;

};


/*************************************************************************************************************************
 Class interface for LibPrimesFactorizationCalculator 
**************************************************************************************************************************/

class ILibPrimesFactorizationCalculator : public virtual ILibPrimesBaseClass, public virtual ILibPrimesCalculator {
public:
	/**
	* IFactorizationCalculator::GetPrimeFactors - Returns the prime factors of this number (without multiplicity)
	* @param[in] nPrimeFactorsBufferSize - Number of elements in buffer
	* @param[out] pPrimeFactorsNeededCount - will be filled with the count of the written structs, or needed buffer size.
	* @param[out] pPrimeFactorsBuffer - PrimeFactor buffer of The prime factors of this number
	*/
	virtual void GetPrimeFactors (LibPrimes_uint64 nPrimeFactorsBufferSize, LibPrimes_uint64* pPrimeFactorsNeededCount, sLibPrimesPrimeFactor * pPrimeFactorsBuffer) = 0;

};


/*************************************************************************************************************************
 Class interface for LibPrimesSieveCalculator 
**************************************************************************************************************************/

class ILibPrimesSieveCalculator : public virtual ILibPrimesBaseClass, public virtual ILibPrimesCalculator {
public:
	/**
	* ISieveCalculator::GetPrimes - Returns all prime numbers lower or equal to the sieve's value
	* @param[in] nPrimesBufferSize - Number of elements in buffer
	* @param[out] pPrimesNeededCount - will be filled with the count of the written structs, or needed buffer size.
	* @param[out] pPrimesBuffer - uint64 buffer of The primes lower or equal to the sieve's value
	*/
	virtual void GetPrimes (LibPrimes_uint64 nPrimesBufferSize, LibPrimes_uint64* pPrimesNeededCount, LibPrimes_uint64 * pPrimesBuffer) = 0;

};


/*************************************************************************************************************************
 Global functions declarations
**************************************************************************************************************************/
class CLibPrimesWrapper {
public:
	/**
	* Ilibprimes::ReleaseInstance - Releases the memory of an Instance
	* @param[in] pInstance - Instance Handle
	*/
	static void ReleaseInstance (ILibPrimesBaseClass* pInstance);

	/**
	* Ilibprimes::GetLibraryVersion - retrieves the current version of the library.
	* @param[out] nMajor - returns the major version of the library
	* @param[out] nMinor - returns the minor version of the library
	* @param[out] nMicro - returns the micro version of the library
	*/
	static void GetLibraryVersion (LibPrimes_uint32 & nMajor, LibPrimes_uint32 & nMinor, LibPrimes_uint32 & nMicro);

	/**
	* Ilibprimes::CreateFactorizationCalculator - Creates a new FactorizationCalculator instance
	* @return New FactorizationCalculator instance
	*/
	static ILibPrimesFactorizationCalculator * CreateFactorizationCalculator ();

	/**
	* Ilibprimes::CreateSieveCalculator - Creates a new SieveCalculator instance
	* @return New SieveCalculator instance
	*/
	static ILibPrimesSieveCalculator * CreateSieveCalculator ();

	/**
	* Ilibprimes::SetJournal - Handles Library Journaling
	* @param[in] sFileName - Journal FileName
	*/
	static void SetJournal (const std::string & sFileName);

};

}

#endif // __LIBPRIMES_CPPINTERFACES
