/*++

Copyright (C) 2018 Autodesk

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.0-develop.

Abstract: This is an autogenerated C++ application that demonstrates the
 usage of the C++ bindings of ACT UnitTest FrameWork

Interface version: 1.0.0

*/

#include <iostream>
#include "libunittest_implicit.hpp"


int main()
{
	try
	{
		auto wrapper = LibUnitTest::CWrapper::loadLibrary();
		LibUnitTest_uint32 nMajor, nMinor, nMicro;
		wrapper->GetVersion(nMajor, nMinor, nMicro);
		std::cout << "LibUnitTest.Version = " << nMajor << "." << nMinor << "." << nMicro;
		std::cout << std::endl;
	}
	catch (std::exception &e)
	{
		std::cout << e.what() << std::endl;
		return 1;
	}
	return 0;
}

