/*++

Copyright (C) 2019 Numbers developers

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.7.0-develop.

Abstract: This is an autogenerated Java file in order to allow an easy
 use of Numbers library

Interface version: 1.0.0

*/

package numbers;

import com.sun.jna.*;

	@Structure.FieldOrder({"Handle", "ClassTypeId"})
	public class NumbersHandle extends Structure {
		public Pointer Handle;
		public long ClassTypeId;
		
		public static class ByValue extends NumbersHandle implements Structure.ByValue {
			public ByValue() { super(); read(); }
			public ByValue(NumbersHandle h) { super(h); read(); }
		}
		public NumbersHandle() { Handle = Pointer.NULL; ClassTypeId = 0; }
		public NumbersHandle(NumbersHandle h) { super(h.getPointer()); read(); }
		public ByValue Value() { return new ByValue(this); }
	}

