/*++

Copyright (C) 2019 Calculator developers

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.6.0-RC1.

Abstract: This is an autogenerated C++ Header file with the basic internal
 exception type in order to allow an easy use of Calculator library

Interface version: 1.0.0

*/

#ifndef __CALCULATOR_INTERFACEEXCEPTION_HEADER
#define __CALCULATOR_INTERFACEEXCEPTION_HEADER

#include <exception>
#include <stdexcept>
#include "calculator_types.hpp"

/*************************************************************************************************************************
 Class ECalculatorInterfaceException
**************************************************************************************************************************/


class ECalculatorInterfaceException : public std::exception {
protected:
	/**
	* Error code for the Exception.
	*/
	CalculatorResult m_errorCode;
	/**
	* Error message for the Exception.
	*/
	std::string m_errorMessage;

public:
	/**
	* Exception Constructor.
	*/
	ECalculatorInterfaceException (CalculatorResult errorCode);

	/**
	* Custom Exception Constructor.
	*/
	ECalculatorInterfaceException (CalculatorResult errorCode, std::string errorMessage);

	/**
	* Returns error code
	*/
	CalculatorResult getErrorCode ();
	/**
	* Returns error message
	*/
	const char* what () const noexcept override;
};

#endif // __CALCULATOR_INTERFACEEXCEPTION_HEADER
