#!/usr/bin/env python3
import os, subprocess, sys, shutil, argparse
from pathlib import Path

CMAKE_TEMPLATE = """
cmake_minimum_required(VERSION 3.13)
project({project_name_upper}_WASM_Build CXX)
set(CMAKE_CXX_STANDARD 17)

set(COMPONENT_ROOT_DIR ${{CMAKE_CURRENT_SOURCE_DIR}}/../..)
get_filename_component(COMPONENT_ROOT_DIR_ABS ${{COMPONENT_ROOT_DIR}} ABSOLUTE)

set(IMPL_DIR ${{COMPONENT_ROOT_DIR_ABS}}/Implementations/Cpp)
message(STATUS "Found Implementation sources at: ${{IMPL_DIR}}")

set(INTERFACES_DIR ${{IMPL_DIR}}/Interfaces)
file(GLOB STUB_SRC "${{IMPL_DIR}}/Stub/*.cpp")
set({project_name_upper}_SRC
    ${{STUB_SRC}}
    "${{INTERFACES_DIR}}/{project_name_lower}_interfaceexception.cpp"
    "${{INTERFACES_DIR}}/{project_name_lower}_interfacewrapper.cpp"
)

add_library({project_name_lower} STATIC ${{{project_name_upper}_SRC}})
target_include_directories({project_name_lower} PUBLIC "${{IMPL_DIR}}/Stub" "${{INTERFACES_DIR}}")

set(BINDINGS_DIR ${{COMPONENT_ROOT_DIR_ABS}}/Bindings)
add_executable(${{WASM_OUTPUT_NAME}} ${{WASM_BINDING_FILE}})
target_include_directories(${{WASM_OUTPUT_NAME}} PRIVATE "${{BINDINGS_DIR}}")
target_link_libraries(${{WASM_OUTPUT_NAME}} PRIVATE {project_name_lower})

# IMPORTANT: use -s<FLAG>=<VALUE> or SHELL: to avoid CMake splitting
target_link_options(${{WASM_OUTPUT_NAME}} PRIVATE
    "-sWASM=1"
    "-sMODULARIZE=1"
    "-sEXPORT_ES6=1"
    "-sEXPORT_NAME={wasm_output_name}"
    "-sUSE_ES6_IMPORT_META=1"
    "-sENVIRONMENT=node"
    "-sALLOW_MEMORY_GROWTH=1"
    "-sMAXIMUM_MEMORY=4294967296"
    "-sINITIAL_MEMORY=1073741824"
    "SHELL:-sEXPORTED_RUNTIME_METHODS=['ccall','cwrap']"
    "--bind"
    "SHELL:-sEXCEPTION_CATCHING_ALLOWED=['*']"
    "-sASSERTIONS=1"
    "--no-entry"
)

set_target_properties(${{WASM_OUTPUT_NAME}} PROPERTIES OUTPUT_NAME "${{WASM_OUTPUT_NAME}}")
"""

# Use sentinel tokens so we don't fight Python's .format with JS braces.
EXAMPLE_JS_TEMPLATE = r"""
// Autogenerated. Runs under Node ESM, loads either ES6+MODULARIZE or legacy global Module.

import path from 'node:path';
import {{ fileURLToPath }} from 'node:url';
const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const JS_NAME  = './<WASM_NAME>.js';
const WASM_URL = new URL('./<WASM_NAME>.wasm', import.meta.url).href;

function assert(c, m) {{ if (!c) throw new Error(m || 'Assertion failed'); }}

async function loadModule() {{
  // Try ES6 + MODULARIZE (default export is a factory)
  const ns = await import(JS_NAME);
  if (typeof ns.default === 'function') {{
    return await ns.default({{
      locateFile: (p) => (p.endsWith('.wasm') ? WASM_URL : p)
    }});
  }}

  // Fallback: non-modularized Emscripten that expects global Module
  globalThis.Module = {{
    locateFile: (p) => (p.endsWith('.wasm') ? WASM_URL : p),
  }};
  await import(JS_NAME);
  await new Promise((res) => {{
    if (!Module.onRuntimeInitialized || Module.calledRun) return res();
    const prev = Module.onRuntimeInitialized;
    Module.onRuntimeInitialized = () => {{ try {{ prev?.() }} finally {{ res(); }} }};
  }});
  return Module;
}}

console.log('Running <PROJ_UPPER> WASM Example...');
(async () => {{
  const mod = await loadModule();
  console.log('✅ <PROJ_UPPER> WASM module initialized');

  const wrapper = new mod.CWrapper();

  // embind returns an object here
  const {{ Major, Minor, Micro }} = wrapper.GetVersion();
  console.log('<PROJ_UPPER> version: ' + Major + '.' + Minor + '.' + Micro);

  const zoo  = wrapper.CreateZoo(); assert(zoo,  'Failed to create Zoo');
  const iter = zoo.Iterator();      assert(iter, 'Failed to create Iterator');

  let animal, count = 0;
  while ((animal = iter.GetNextAnimal())) {{
    count++;
    const name = animal.Name();
    console.log(`Processing animal #${{count}}: ${{name}}`);

    // Classes are prefixed with C in the bindings
    if (name === 'Gerald Giraffe' || name === 'Gary Giraffe') {{
      assert(animal instanceof mod.CGiraffe, `Expected ${{name}} to be a Giraffe`);
    }} else if (name === 'Timmy Tiger' || name === 'Tony Tiger' || name === 'Travis Tiger') {{
      assert(animal instanceof mod.CTiger, `Expected ${{name}} to be a Tiger`); animal.Roar();
    }} else if (name === 'Sebastian Snake' || name === 'Slytherin Snake') {{
      assert(animal instanceof mod.CSnake, `Expected ${{name}} to be a Snake`);
    }} else if (name.includes('Turtle')) {{
      assert(animal instanceof mod.CTurtle, `Expected ${{name}} to be a Turtle`);
    }} else {{
      console.warn(`Unknown animal type for ${{name}}`);
    }}

    animal.delete();
  }}

  const noMore = iter.GetNextAnimal();
  assert(!noMore, 'Iterator should be exhausted after the loop');
  if (noMore) noMore.delete();

  console.log(`\n✅ Successfully processed ${{count}} animals.`);
  iter.delete(); zoo.delete(); wrapper.delete();
}})().catch((err) => {{ console.error('Error:', err); process.exit(1); }});
"""

def run_command(cmd, wd):
    try:
        p = subprocess.run(cmd, cwd=wd, check=True, capture_output=True, text=True, encoding='utf-8')
        if p.stdout: print(p.stdout)
        return True
    except FileNotFoundError:
        print(f"Error: Command '{cmd[0]}' not found. Is it in your PATH?", file=sys.stderr); return False
    except subprocess.CalledProcessError as e:
        print(f"Error: Command failed with exit code {e.returncode}.", file=sys.stderr)
        print(f"--- STDOUT ---\n{e.stdout}", file=sys.stderr)
        print(f"--- STDERR ---\n{e.stderr}", file=sys.stderr)
        return False

def main():
    ap = argparse.ArgumentParser(description="Generates and builds a WASM binding for an ACT component.")
    ap.add_argument("--no-cleanup", dest='cleanup', action='store_false',
                    help="Do not remove build artifacts after a successful build.")
    args = ap.parse_args()

    script_dir = Path(__file__).parent.resolve()
    build_dir = script_dir / "build"
    cmake_file = script_dir / "CMakeLists.txt"

    # Clean old
    if build_dir.exists(): shutil.rmtree(build_dir)
    if cmake_file.exists(): cmake_file.unlink()
    for pattern in ["*Binding.js", "*Binding.wasm"]:
        for f in script_dir.glob(pattern): f.unlink()

    # Discover
    component_root = script_dir.parent.parent
    if not component_root.name.endswith("_component"):
        sys.exit("Fatal: wrong directory structure")
    project_name = component_root.name.replace("_component","")
    project_name_lower = project_name.lower()

    bind_dir = component_root / "Bindings" / "WASM"
    binding_files = list(bind_dir.glob("*_bindings.cpp"))
    if len(binding_files) != 1:
        sys.exit("Fatal: expected exactly one *_bindings.cpp in Bindings/WASM")
    binding_cpp = binding_files[0]

    wasm_output_name = f"{binding_cpp.stem.replace('_bindings','')}Binding"

    # Ensure ESM for Node
    (script_dir / "package.json").write_text('{ "type": "module" }\n', encoding='utf-8')

    # Write CMakeLists
    cmake_file.write_text(
        CMAKE_TEMPLATE.format(
            project_name_lower=project_name_lower,
            project_name_upper=project_name.upper(),
            wasm_output_name=wasm_output_name
        ).strip(),
        encoding='utf-8'
    )

    # Configure + build
    build_dir.mkdir(exist_ok=True)
    if not run_command(
        ["emcmake", "cmake",
         f"-DWASM_BINDING_FILE={binding_cpp}",
         f"-DWASM_OUTPUT_NAME={wasm_output_name}",
         "-S", str(script_dir), "-B", str(build_dir)],
        script_dir
    ):
        sys.exit("CMake configuration failed.")
    if not run_command(["cmake", "--build", str(build_dir)], script_dir):
        sys.exit("Build failed.")

    # Write example.js (token replacement, not .format)
    example_js = script_dir / "example.js"
    js_text = EXAMPLE_JS_TEMPLATE.replace("<PROJ_UPPER>", project_name.upper()) \
                                 .replace("<WASM_NAME>", wasm_output_name)
    example_js.write_text(js_text.strip(), encoding='utf-8')

    # Move artifacts
    if args.cleanup:
        for ext in [".js", ".wasm"]:
            src = build_dir / (wasm_output_name + ext)
            if src.exists():
                shutil.move(str(src), str(script_dir))
        shutil.rmtree(build_dir)
        cmake_file.unlink()

    print("\nDone. Run:\n  node example.js\n")

if __name__ == "__main__":
    main()
