#!/usr/bin/env python3
import os
import subprocess
import sys
import shutil
import argparse
from pathlib import Path

# CMake template with dynamic EXPORT_NAME
CMAKE_TEMPLATE = """
cmake_minimum_required(VERSION 3.13)
project({project_name_upper}_WASM_Build CXX)

set(CMAKE_CXX_STANDARD 17)

set(COMPONENT_ROOT_DIR ${{CMAKE_CURRENT_SOURCE_DIR}}/../..)
get_filename_component(COMPONENT_ROOT_DIR_ABS ${{COMPONENT_ROOT_DIR}} ABSOLUTE)

set(IMPL_DIR ${{COMPONENT_ROOT_DIR_ABS}}/Implementations/Cpp)
message(STATUS "Found Implementation sources at: ${{IMPL_DIR}}")

set(INTERFACES_DIR ${{IMPL_DIR}}/Interfaces)
file(GLOB STUB_SRC "${{IMPL_DIR}}/Stub/*.cpp")
set({project_name_upper}_SRC
    ${{STUB_SRC}}
    "${{INTERFACES_DIR}}/{project_name_lower}_interfaceexception.cpp"
    "${{INTERFACES_DIR}}/{project_name_lower}_interfacewrapper.cpp"
)

add_library({project_name_lower} STATIC ${{{project_name_upper}_SRC}})

target_include_directories({project_name_lower} PUBLIC
    "${{IMPL_DIR}}/Stub"
    "${{INTERFACES_DIR}}"
)

set(BINDINGS_DIR ${{COMPONENT_ROOT_DIR_ABS}}/Bindings)
add_executable(${{WASM_OUTPUT_NAME}} ${{WASM_BINDING_FILE}})

target_include_directories(${{WASM_OUTPUT_NAME}} PRIVATE
    "${{BINDINGS_DIR}}"
)

target_link_libraries(${{WASM_OUTPUT_NAME}} PRIVATE {project_name_lower})

target_link_options(${{WASM_OUTPUT_NAME}} PRIVATE
    "-s WASM=1"
    "-s MODULARIZE=1"
    "-s EXPORT_ES6=1"
    "-s EXPORT_NAME={wasm_output_name}"
    "-s USE_ES6_IMPORT_META=1"
    "-s ALLOW_MEMORY_GROWTH=1"
    "-s MAXIMUM_MEMORY=4294967296"
    "-s INITIAL_MEMORY=1073741824"
    "-s EXPORTED_RUNTIME_METHODS=['ccall','cwrap']"
    "--bind"
    "-s EXCEPTION_CATCHING_ALLOWED=['*']"
    "-s ASSERTIONS=1"
    "--no-entry"
)

set_target_properties(${{WASM_OUTPUT_NAME}} PROPERTIES OUTPUT_NAME "${{WASM_OUTPUT_NAME}}")
"""

# Example.js template updated to import the named export
EXAMPLE_JS_TEMPLATE = """
// This file was autogenerated by build_wasm.py.
// It demonstrates how to use the {project_name_upper} WASM module.

import {{ {wasm_output_name} as initModule }} from './{wasm_output_name}.js';

console.log('Running {project_name_upper} WASM Example...');

function assert(condition, message) {{
    if (!condition) {{
        throw new Error(message || "Assertion failed");
    }}
}}

initModule().then(rtti => {{
    console.log("✅ {project_name_upper} WASM module initialized");

    const wrapper = new rtti.CWrapper();
    const [major, minor, micro] = wrapper.GetVersion();
    console.log(`{project_name_upper} version: ${{major}}.${{minor}}.${{micro}}`);

    const zoo = wrapper.CreateZoo();
    assert(zoo, "Failed to create Zoo");

    const iter = zoo.Iterator();
    assert(iter, "Failed to create Iterator");

    let animal;
    let animalCount = 0;

    while ((animal = iter.GetNextAnimal())) {{
        animalCount++;
        const name = animal.Name();
        console.log(`Processing animal #${{animalCount}}: ${{name}}`);

        if (name === "Gerald Giraffe" || name === "Gary Giraffe") {{
            assert(animal instanceof rtti.Giraffe, `Expected ${{name}} to be a Giraffe`);
        }} else if (name === "Timmy Tiger" || name === "Tony Tiger" || name === "Travis Tiger") {{
            assert(animal instanceof rtti.Tiger, `Expected ${{name}} to be a Tiger`);
            animal.Roar();
        }} else if (name === "Sebastian Snake" || name === "Slytherin Snake") {{
            assert(animal instanceof rtti.Snake, `Expected ${{name}} to be a Snake`);
        }} else if (name.includes("Turtle")) {{
            assert(animal instanceof rtti.Turtle, `Expected ${{name}} to be a Turtle`);
        }} else {{
            console.warn(`Unknown animal type for ${{name}}`);
        }}

        animal.delete();
    }}

    const noMoreAnimals = iter.GetNextAnimal();
    assert(!noMoreAnimals, "Iterator should be exhausted after the loop");
    if (noMoreAnimals) noMoreAnimals.delete();

    console.log(`\\n✅ Successfully processed ${{animalCount}} animals.`);

    iter.delete();
    zoo.delete();
    wrapper.delete();
}}).catch(err => {{
    console.error("Error:", err);
    process.exit(1);
}});
"""

def run_command(command, working_directory):
    try:
        process = subprocess.run(
            command, cwd=working_directory, check=True, capture_output=True,
            text=True, encoding='utf-8'
        )
        if process.stdout:
            print(process.stdout)
        return True
    except FileNotFoundError:
        print(f"Error: Command '{command[0]}' not found. Is it in your PATH?", file=sys.stderr)
        return False
    except subprocess.CalledProcessError as e:
        print(f"Error: Command failed with exit code {e.returncode}.", file=sys.stderr)
        print(f"--- STDOUT ---\n{e.stdout}", file=sys.stderr)
        print(f"--- STDERR ---\n{e.stderr}", file=sys.stderr)
        return False

def main():
    parser = argparse.ArgumentParser(description="Generates and builds a WASM binding for an ACT component.")
    parser.add_argument("--no-cleanup", dest='cleanup', action='store_false',
                        help="Do not remove build artifacts after a successful build.")
    args = parser.parse_args()

    script_dir = Path(__file__).parent.resolve()
    build_dir = script_dir / "build"
    cmake_file_path = script_dir / "CMakeLists.txt"

    # Clean up old artifacts
    if build_dir.exists():
        shutil.rmtree(build_dir)
    if cmake_file_path.exists():
        cmake_file_path.unlink()
    for pattern in ["*Binding.js", "*Binding.wasm"]:
        for old_file in script_dir.glob(pattern):
            old_file.unlink()

    # Discover component and binding file
    component_root_dir = script_dir.parent.parent
    if not component_root_dir.name.endswith("_component"):
        sys.exit("Fatal: wrong directory structure")
    project_name = component_root_dir.name.replace("_component", "")
    project_name_lower = project_name.lower()

    bindings_wasm_dir = component_root_dir / "Bindings" / "WASM"
    binding_files = list(bindings_wasm_dir.glob("*_bindings.cpp"))
    if len(binding_files) != 1:
        sys.exit("Fatal: expected exactly one *_bindings.cpp in Bindings/WASM")
    binding_file_path = binding_files[0]

    wasm_output_name = f"{binding_file_path.stem.replace('_bindings','')}Binding"

    # Write package.json to enforce ES module
    (script_dir / "package.json").write_text('{ "type": "module" }\n', encoding='utf-8')

    # Write CMakeLists.txt
    cmake_content = CMAKE_TEMPLATE.format(
        project_name_lower=project_name_lower,
        project_name_upper=project_name.upper(),
        wasm_output_name=wasm_output_name
    )
    cmake_file_path.write_text(cmake_content.strip(), encoding='utf-8')

    # Configure and build with Emscripten
    build_dir.mkdir(exist_ok=True)
    if not run_command(
        ["emcmake", "cmake",
         f"-DWASM_BINDING_FILE={binding_file_path}",
         f"-DWASM_OUTPUT_NAME={wasm_output_name}",
         "-S", str(script_dir), "-B", str(build_dir)],
        script_dir
    ):
        sys.exit("CMake configuration failed.")
    if not run_command(["cmake", "--build", str(build_dir)], script_dir):
        sys.exit("Build failed.")

    # Write out the example.js
    example_path = script_dir / "example.js"
    example_content = EXAMPLE_JS_TEMPLATE.format(
        project_name_upper=project_name.upper(),
        wasm_output_name=wasm_output_name
    )
    example_path.write_text(example_content.strip(), encoding='utf-8')

    # Optional cleanup
    if args.cleanup:
        for ext in [".js", ".wasm"]:
            art = build_dir / (wasm_output_name + ext)
            if art.exists():
                shutil.move(str(art), str(script_dir))
        shutil.rmtree(build_dir)
        cmake_file_path.unlink()

if __name__ == "__main__":
    main()
