/*++

Copyright (C) 2019 Calculation developers

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.7.0-develop.

Abstract: This is an autogenerated Java file in order to allow an easy
 use of Calculation library

Interface version: 1.0.0

*/

package calculation;

import com.sun.jna.*;

	@Structure.FieldOrder({"Handle", "ClassTypeId"})
	public class CalculationHandle extends Structure {
		public Pointer Handle;
		public long ClassTypeId;
		
		public static class ByValue extends CalculationHandle implements Structure.ByValue {
			public ByValue() { super(); read(); }
			public ByValue(CalculationHandle h) { super(h); read(); }
		}
		public CalculationHandle() { Handle = Pointer.NULL; ClassTypeId = 0; }
		public CalculationHandle(CalculationHandle h) { super(h.getPointer()); read(); }
		public ByValue Value() { return new ByValue(this); }
	}

