/*++

Copyright (C) 2018 Autodesk

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.0-develop.

Abstract: This is an autogenerated Go application that demonstrates the
 usage of the Go bindings of ACT UnitTest FrameWork

Interface version: 1.0.0

*/


package main

import (
	"fmt"
	"log"
	"../../Bindings/Go"
)

func main() {
	nMajor, nMinor, nMicro, err := GetVersion()
	if err != nil {
		log.Fatal(err)
	}
	versionString := fmt.Sprintf("libunittest.version = %d.%d.%d", nMajor, nMinor, nMicro)
	
	fmt.Println(versionString)
}

