(*++

Copyright (C) 2018 Autodesk

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.1-develop.

Abstract: This is an autogenerated Pascal exception class definition file in order to allow easy
development of ACT UnitTest FrameWork. The functions in this file need to be implemented. It needs to be generated only once.

Interface version: 1.0.0

*)

{$MODE DELPHI}
unit libunittest_exception;

interface

uses
  libunittest_types,
  libunittest_interfaces,
  Classes,
  sysutils;

type
  ELibUnitTestException = class(Exception)
  private
    FErrorCode: TLibUnitTestResult;
    FCustomMessage: String;
  public
    property ErrorCode: TLibUnitTestResult read FErrorCode;
    property CustomMessage: String read FCustomMessage;
    constructor Create(AErrorCode: TLibUnitTestResult);
    constructor CreateCustomMessage(AErrorCode: TLibUnitTestResult; AMessage: String);
  end;


(*************************************************************************************************************************
 Definition of exception handling functionality for LibUnitTest
**************************************************************************************************************************)

function HandleLibUnitTestException(ALibUnitTestObject: TObject; E: ELibUnitTestException): TLibUnitTestResult;
function HandleStdException(ALibUnitTestObject: TObject; E: Exception): TLibUnitTestResult;
function HandleUnhandledException(ALibUnitTestObject: TObject): TLibUnitTestResult;


implementation

  constructor ELibUnitTestException.Create(AErrorCode: TLibUnitTestResult);
  var
    ADescription: String;
  begin
    FErrorCode := AErrorCode;
    case FErrorCode of
      LIBUNITTEST_ERROR_NOTIMPLEMENTED: ADescription := 'functionality not implemented';
      LIBUNITTEST_ERROR_INVALIDPARAM: ADescription := 'an invalid parameter was passed';
      LIBUNITTEST_ERROR_INVALIDCAST: ADescription := 'a type cast failed';
      LIBUNITTEST_ERROR_BUFFERTOOSMALL: ADescription := 'a provided buffer is too small';
      LIBUNITTEST_ERROR_GENERICEXCEPTION: ADescription := 'a generic exception occurred';
      LIBUNITTEST_ERROR_COULDNOTLOADLIBRARY: ADescription := 'the library could not be loaded';
      LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT: ADescription := 'a required exported symbol could not be found in the library';
      LIBUNITTEST_ERROR_INCOMPATIBLEBINARYVERSION: ADescription := 'the version of the binary interface does not match the bindings interface';
      else
        ADescription := 'unknown';
    end;

    inherited Create(Format('ACT UnitTest FrameWork Error - %s (#%d)', [ ADescription, AErrorCode ]));
  end;

  constructor ELibUnitTestException.CreateCustomMessage(AErrorCode: TLibUnitTestResult; AMessage: String);
  begin
    FCustomMessage := AMessage;
    FErrorCode := AErrorCode;
    inherited Create(Format('%s(%d)', [FCustomMessage, AErrorCode]));
  end;

(*************************************************************************************************************************
 Implementation of exception handling functionality for LibUnitTest
**************************************************************************************************************************)

function HandleLibUnitTestException(ALibUnitTestObject: TObject; E: ELibUnitTestException): TLibUnitTestResult;
begin
  result := E.ErrorCode;
  if Supports(ALibUnitTestObject, ILibUnitTestBase) then begin
    (ALibUnitTestObject as ILibUnitTestBase).RegisterErrorMessage(E.CustomMessage)
  end;
end;
function HandleStdException(ALibUnitTestObject: TObject; E: Exception): TLibUnitTestResult;
begin
  Result := LIBUNITTEST_ERROR_GENERICEXCEPTION;
  if Supports(ALibUnitTestObject, ILibUnitTestBase) then begin
    (ALibUnitTestObject as ILibUnitTestBase).RegisterErrorMessage(E.Message)
  end;
end;
function HandleUnhandledException(ALibUnitTestObject: TObject): TLibUnitTestResult;
begin
  Result := LIBUNITTEST_ERROR_GENERICEXCEPTION;
  if Supports(ALibUnitTestObject, ILibUnitTestBase) then begin
    (ALibUnitTestObject as ILibUnitTestBase).RegisterErrorMessage('Unhandled Exception')
  end;
end;
end.
