(*++

Copyright (C) 2018 Autodesk

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.0-develop.

Abstract: This is an autogenerated Pascal project file in order to allow easy
development of ACT UnitTest FrameWork.

Interface version: 1.0.0

*)

{$MODE DELPHI}
library libunittest;

uses
{$IFDEF UNIX}
  cthreads,
{$ENDIF UNIX}
  syncobjs,
  libunittest_types,
  libunittest_exports,
  Classes,
  sysutils;

exports
  libunittest_base_classtypeid,
  libunittest_testclass_value,
  libunittest_testclass_setvalue,
  libunittest_testclass_setvalueint,
  libunittest_testclass_setvaluestring,
  libunittest_testclass_unittest1,
  libunittest_testclass_unittest2,
  libunittest_testclass_unittest3,
  libunittest_testclass_unittest4,
  libunittest_getversion,
  libunittest_getlasterror,
  libunittest_releaseinstance,
  libunittest_acquireinstance,
  libunittest_injectcomponent,
  libunittest_getsymbollookupmethod,
  libunittest_createtestclasss;

{$IFDEF LIBUNITTEST_INCLUDE_RES_FILE}
{$R *.res}
{$ENDIF LIBUNITTEST_INCLUDE_RES_FILE}

begin

end.
