'''++

Copyright (C) 2019 Numbers developers

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.1-alpha.

Abstract: This is an autogenerated Python file in order to allow an easy
 use of Numbers library

Interface version: 1.0.0

'''


import ctypes
import platform
import enum
import os

name = "numbers"

'''Definition of domain specific exception
'''
class ENumbersException(Exception):
	def __init__(self, code, message = ''):
		self._code = code
		self._message = message
	
	def __str__(self):
		if self._message:
			return 'NumbersException ' + str(self._code) + ': '+ str(self._message)
		return 'NumbersException ' + str(self._code)
	
	def get_error_code(self):
		"""Returns the error code"""
		return self._code
	
	def get_error_message(self):
		"""Returns the custom error message"""
		return self._message
	
	def get_error_name(self):
		"""Returns the error name (constant name)"""
		if self._code == ErrorCodes.SUCCESS:
			return 'SUCCESS'
		elif self._code == ErrorCodes.NOTIMPLEMENTED:
			return 'NOTIMPLEMENTED'
		elif self._code == ErrorCodes.INVALIDPARAM:
			return 'INVALIDPARAM'
		elif self._code == ErrorCodes.INVALIDCAST:
			return 'INVALIDCAST'
		elif self._code == ErrorCodes.BUFFERTOOSMALL:
			return 'BUFFERTOOSMALL'
		elif self._code == ErrorCodes.GENERICEXCEPTION:
			return 'GENERICEXCEPTION'
		elif self._code == ErrorCodes.COULDNOTLOADLIBRARY:
			return 'COULDNOTLOADLIBRARY'
		elif self._code == ErrorCodes.COULDNOTFINDLIBRARYEXPORT:
			return 'COULDNOTFINDLIBRARYEXPORT'
		elif self._code == ErrorCodes.INCOMPATIBLEBINARYVERSION:
			return 'INCOMPATIBLEBINARYVERSION'
		else:
			return 'UNKNOWN'
	
	def get_error_description(self):
		"""Returns the error description (human-readable)"""
		if self._code == ErrorCodes.SUCCESS:
			return 'success'
		elif self._code == ErrorCodes.NOTIMPLEMENTED:
			return 'functionality not implemented'
		elif self._code == ErrorCodes.INVALIDPARAM:
			return 'an invalid parameter was passed'
		elif self._code == ErrorCodes.INVALIDCAST:
			return 'a type cast failed'
		elif self._code == ErrorCodes.BUFFERTOOSMALL:
			return 'a provided buffer is too small'
		elif self._code == ErrorCodes.GENERICEXCEPTION:
			return 'a generic exception occurred'
		elif self._code == ErrorCodes.COULDNOTLOADLIBRARY:
			return 'the library could not be loaded'
		elif self._code == ErrorCodes.COULDNOTFINDLIBRARYEXPORT:
			return 'a required exported symbol could not be found in the library'
		elif self._code == ErrorCodes.INCOMPATIBLEBINARYVERSION:
			return 'the version of the binary interface does not match the bindings interface'
		else:
			return 'unknown error'
	
	@property
	def error_code(self):
		"""Property to access error code"""
		return self._code
	
	@property
	def error_message(self):
		"""Property to access custom error message"""
		return self._message
	
	@property
	def error_name(self):
		"""Property to access error name"""
		return self.get_error_name()
	
	@property
	def error_description(self):
		"""Property to access error description"""
		return self.get_error_description()

'''Definition of binding API version
'''
class BindingVersion(enum.IntEnum):
	MAJOR = 1
	MINOR = 0
	MICRO = 0

'''Definition Error Codes
'''
class ErrorCodes(enum.IntEnum):
	SUCCESS = 0
	NOTIMPLEMENTED = 1
	INVALIDPARAM = 2
	INVALIDCAST = 3
	BUFFERTOOSMALL = 4
	GENERICEXCEPTION = 5
	COULDNOTLOADLIBRARY = 6
	COULDNOTFINDLIBRARYEXPORT = 7
	INCOMPATIBLEBINARYVERSION = 8

'''Definition of Function Table
'''
class FunctionTable:
	numbers_createvariable = None
	numbers_getversion = None
	numbers_getlasterror = None
	numbers_releaseinstance = None
	numbers_acquireinstance = None
	numbers_getsymbollookupmethod = None
	numbers_base_classtypeid = None
	numbers_variable_getvalue = None
	numbers_variable_setvalue = None


'''Wrapper Class Implementation
'''
class Wrapper:

	def __init__(self, libraryName = None, symbolLookupMethodAddress = None):
		ending = ''
		if platform.system() == 'Windows':
			ending = 'dll'
		elif platform.system() == 'Linux':
			ending = 'so'
		elif platform.system() == 'Darwin':
			ending = 'dylib'
		else:
			raise ENumbersException(ErrorCodes.COULDNOTLOADLIBRARY)
		
		if (not libraryName) and (not symbolLookupMethodAddress):
			libraryName = os.path.join(os.path.dirname(os.path.realpath(__file__)),'numbers')
		
		if libraryName is not None:
			path = libraryName + '.' + ending
			try:
				self.lib = ctypes.CDLL(path)
			except Exception as e:
				raise ENumbersException(ErrorCodes.COULDNOTLOADLIBRARY, str(e) + '| "'+path + '"' )
			
			self._loadFunctionTable()
		elif symbolLookupMethodAddress is not None:
				self.lib = FunctionTable()
				self._loadFunctionTableFromMethod(symbolLookupMethodAddress)
		else:
			raise ENumbersException(ErrorCodes.COULDNOTLOADLIBRARY, str(e))
		
		self._checkBinaryVersion()
	
	def _loadFunctionTableFromMethod(self, symbolLookupMethodAddress):
		try:
			symbolLookupMethodType = ctypes.CFUNCTYPE(ctypes.c_int32, ctypes.c_char_p, ctypes.POINTER(ctypes.c_void_p))
			symbolLookupMethod = symbolLookupMethodType(int(symbolLookupMethodAddress))
			
			methodAddress = ctypes.c_void_p()
			
			err = symbolLookupMethod(ctypes.c_char_p(str.encode("numbers_createvariable")), methodAddress)
			if err != 0:
				raise ENumbersException(ErrorCodes.COULDNOTLOADLIBRARY, str(err))
			methodType = ctypes.CFUNCTYPE(ctypes.c_int32, ctypes.c_double, ctypes.POINTER(ctypes.c_void_p))
			self.lib.numbers_createvariable = methodType(int(methodAddress.value))
			
			err = symbolLookupMethod(ctypes.c_char_p(str.encode("numbers_getversion")), methodAddress)
			if err != 0:
				raise ENumbersException(ErrorCodes.COULDNOTLOADLIBRARY, str(err))
			methodType = ctypes.CFUNCTYPE(ctypes.c_int32, ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32))
			self.lib.numbers_getversion = methodType(int(methodAddress.value))
			
			err = symbolLookupMethod(ctypes.c_char_p(str.encode("numbers_getlasterror")), methodAddress)
			if err != 0:
				raise ENumbersException(ErrorCodes.COULDNOTLOADLIBRARY, str(err))
			methodType = ctypes.CFUNCTYPE(ctypes.c_int32, ctypes.c_void_p, ctypes.c_uint64, ctypes.POINTER(ctypes.c_uint64), ctypes.c_char_p, ctypes.POINTER(ctypes.c_bool))
			self.lib.numbers_getlasterror = methodType(int(methodAddress.value))
			
			err = symbolLookupMethod(ctypes.c_char_p(str.encode("numbers_releaseinstance")), methodAddress)
			if err != 0:
				raise ENumbersException(ErrorCodes.COULDNOTLOADLIBRARY, str(err))
			methodType = ctypes.CFUNCTYPE(ctypes.c_int32, ctypes.c_void_p)
			self.lib.numbers_releaseinstance = methodType(int(methodAddress.value))
			
			err = symbolLookupMethod(ctypes.c_char_p(str.encode("numbers_acquireinstance")), methodAddress)
			if err != 0:
				raise ENumbersException(ErrorCodes.COULDNOTLOADLIBRARY, str(err))
			methodType = ctypes.CFUNCTYPE(ctypes.c_int32, ctypes.c_void_p)
			self.lib.numbers_acquireinstance = methodType(int(methodAddress.value))
			
			err = symbolLookupMethod(ctypes.c_char_p(str.encode("numbers_getsymbollookupmethod")), methodAddress)
			if err != 0:
				raise ENumbersException(ErrorCodes.COULDNOTLOADLIBRARY, str(err))
			methodType = ctypes.CFUNCTYPE(ctypes.c_int32, ctypes.POINTER(ctypes.c_void_p))
			self.lib.numbers_getsymbollookupmethod = methodType(int(methodAddress.value))
			
			err = symbolLookupMethod(ctypes.c_char_p(str.encode("numbers_base_classtypeid")), methodAddress)
			if err != 0:
				raise ENumbersException(ErrorCodes.COULDNOTLOADLIBRARY, str(err))
			methodType = ctypes.CFUNCTYPE(ctypes.c_int32, ctypes.c_void_p, ctypes.POINTER(ctypes.c_uint64))
			self.lib.numbers_base_classtypeid = methodType(int(methodAddress.value))
			
			err = symbolLookupMethod(ctypes.c_char_p(str.encode("numbers_variable_getvalue")), methodAddress)
			if err != 0:
				raise ENumbersException(ErrorCodes.COULDNOTLOADLIBRARY, str(err))
			methodType = ctypes.CFUNCTYPE(ctypes.c_int32, ctypes.c_void_p, ctypes.POINTER(ctypes.c_double))
			self.lib.numbers_variable_getvalue = methodType(int(methodAddress.value))
			
			err = symbolLookupMethod(ctypes.c_char_p(str.encode("numbers_variable_setvalue")), methodAddress)
			if err != 0:
				raise ENumbersException(ErrorCodes.COULDNOTLOADLIBRARY, str(err))
			methodType = ctypes.CFUNCTYPE(ctypes.c_int32, ctypes.c_void_p, ctypes.c_double)
			self.lib.numbers_variable_setvalue = methodType(int(methodAddress.value))
			
		except AttributeError as ae:
			raise ENumbersException(ErrorCodes.COULDNOTFINDLIBRARYEXPORT, ae.args[0])
		
	def _loadFunctionTable(self):
		try:
			self.lib.numbers_createvariable.restype = ctypes.c_int32
			self.lib.numbers_createvariable.argtypes = [ctypes.c_double, ctypes.POINTER(ctypes.c_void_p)]
			
			self.lib.numbers_getversion.restype = ctypes.c_int32
			self.lib.numbers_getversion.argtypes = [ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32)]
			
			self.lib.numbers_getlasterror.restype = ctypes.c_int32
			self.lib.numbers_getlasterror.argtypes = [ctypes.c_void_p, ctypes.c_uint64, ctypes.POINTER(ctypes.c_uint64), ctypes.c_char_p, ctypes.POINTER(ctypes.c_bool)]
			
			self.lib.numbers_releaseinstance.restype = ctypes.c_int32
			self.lib.numbers_releaseinstance.argtypes = [ctypes.c_void_p]
			
			self.lib.numbers_acquireinstance.restype = ctypes.c_int32
			self.lib.numbers_acquireinstance.argtypes = [ctypes.c_void_p]
			
			self.lib.numbers_getsymbollookupmethod.restype = ctypes.c_int32
			self.lib.numbers_getsymbollookupmethod.argtypes = [ctypes.POINTER(ctypes.c_void_p)]
			
			self.lib.numbers_base_classtypeid.restype = ctypes.c_int32
			self.lib.numbers_base_classtypeid.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_uint64)]
			
			self.lib.numbers_variable_getvalue.restype = ctypes.c_int32
			self.lib.numbers_variable_getvalue.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_double)]
			
			self.lib.numbers_variable_setvalue.restype = ctypes.c_int32
			self.lib.numbers_variable_setvalue.argtypes = [ctypes.c_void_p, ctypes.c_double]
			
		except AttributeError as ae:
			raise ENumbersException(ErrorCodes.COULDNOTFINDLIBRARYEXPORT, ae.args[0])
	
	def _checkBinaryVersion(self):
		nMajor, nMinor, _ = self.GetVersion()
		if (nMajor != BindingVersion.MAJOR) or (nMinor < BindingVersion.MINOR):
			raise ENumbersException(ErrorCodes.INCOMPATIBLEBINARYVERSION)
	
	def checkError(self, instance, errorCode):
		ec = globals().get('ErrorCodes')
		if ec is None:
			# Interpreter shutdown: ErrorCodes may already be cleared; avoid noisy teardown
			return
		if errorCode != ec.SUCCESS.value:
			if instance:
				if instance._wrapper != self:
					raise ENumbersException(ec.INVALIDCAST, 'invalid wrapper call')
			message,_ = self.GetLastError(instance)
			raise ENumbersException(errorCode, message)
	
	def CreateVariable(self, InitialValue):
		dInitialValue = ctypes.c_double(InitialValue)
		InstanceHandle = ctypes.c_void_p()
		self.checkError(None, self.lib.numbers_createvariable(dInitialValue, InstanceHandle))
		if InstanceHandle:
			InstanceObject = self._polymorphicFactory(InstanceHandle)
		else:
			raise ENumbersException(ErrorCodes.INVALIDCAST, 'Invalid return/output value')
		
		return InstanceObject
	
	def GetVersion(self, Major = None, Minor = None, Micro = None):
		pMajor = ctypes.c_uint32(Major if Major is not None else 0)
		pMinor = ctypes.c_uint32(Minor if Minor is not None else 0)
		pMicro = ctypes.c_uint32(Micro if Micro is not None else 0)
		self.checkError(None, self.lib.numbers_getversion(pMajor, pMinor, pMicro))
		
		return pMajor.value, pMinor.value, pMicro.value
	
	def GetLastError(self, InstanceObject, ErrorMessage = None):
		InstanceHandle = None
		if InstanceObject:
			InstanceHandle = InstanceObject._handle
		else:
			raise ENumbersException(ErrorCodes.INVALIDPARAM, 'Invalid return/output value')
		nErrorMessageBufferSize = ctypes.c_uint64(len(ErrorMessage) if ErrorMessage else 0)
		nErrorMessageNeededChars = ctypes.c_uint64(0)
		pErrorMessageBuffer = ctypes.c_char_p(str.encode(ErrorMessage) if ErrorMessage else None)
		pHasError = ctypes.c_bool()
		self.checkError(None, self.lib.numbers_getlasterror(InstanceHandle, nErrorMessageBufferSize, nErrorMessageNeededChars, pErrorMessageBuffer, pHasError))
		nErrorMessageBufferSize = ctypes.c_uint64(nErrorMessageNeededChars.value)
		pErrorMessageBuffer = (ctypes.c_char * (nErrorMessageNeededChars.value))()
		self.checkError(None, self.lib.numbers_getlasterror(InstanceHandle, nErrorMessageBufferSize, nErrorMessageNeededChars, pErrorMessageBuffer, pHasError))
		
		return pErrorMessageBuffer.value.decode(), pHasError.value
	
	def ReleaseInstance(self, InstanceObject):
		InstanceHandle = None
		if InstanceObject:
			InstanceHandle = InstanceObject._handle
		else:
			raise ENumbersException(ErrorCodes.INVALIDPARAM, 'Invalid return/output value')
		self.checkError(None, self.lib.numbers_releaseinstance(InstanceHandle))
		
	
	def AcquireInstance(self, InstanceObject):
		InstanceHandle = None
		if InstanceObject:
			InstanceHandle = InstanceObject._handle
		else:
			raise ENumbersException(ErrorCodes.INVALIDPARAM, 'Invalid return/output value')
		self.checkError(None, self.lib.numbers_acquireinstance(InstanceHandle))
		
	
	def GetSymbolLookupMethod(self):
		pSymbolLookupMethod = ctypes.c_void_p()
		self.checkError(None, self.lib.numbers_getsymbollookupmethod(pSymbolLookupMethod))
		
		return pSymbolLookupMethod.value
	
	'''IMPORTANT: PolymorphicFactory method should not be used by application directly.
								It's designed to be used on NumbersHandle object only once.
								If it's used on any existing object as a form of dynamic cast then
								Wrapper.AcquireInstance(object) must be called after instantiating new object.
								This is important to keep reference count matching between application and library sides.
	'''
	def _polymorphicFactory(self, handle):
		class PolymorphicFactory():
			def getObjectById(self, classtypeid, handle, wrapper):
				methodName = 'getObjectById_' + format(classtypeid.value, '016X')
				method = getattr(self, methodName, lambda: 'Invalid class type id')
				return method(handle, wrapper)
			def getObjectById_27799F69B3FD1C9E(self, handle, wrapper): # First 64 bits of SHA1 of a string: "Numbers::Base"
				return Base(handle, wrapper)
			def getObjectById_23934EDF762423EA(self, handle, wrapper): # First 64 bits of SHA1 of a string: "Numbers::Variable"
				return Variable(handle, wrapper)
		
		if not handle:
			return None
		pClassTypeId = ctypes.c_uint64()
		self.checkError(None, self.lib.numbers_base_classtypeid(handle, pClassTypeId))
		factory = PolymorphicFactory()
		return factory.getObjectById(pClassTypeId, handle, self)
	


''' Class Implementation for Base
'''
class Base:
	def __init__(self, handle, wrapper):
		if not handle or not wrapper:
			raise ENumbersException(ErrorCodes.INVALIDPARAM)
		self._handle = handle
		self._wrapper = wrapper
	
	def __del__(self):
		self._wrapper.ReleaseInstance(self)
	def ClassTypeId(self):
		pClassTypeId = ctypes.c_uint64()
		self._wrapper.checkError(self, self._wrapper.lib.numbers_base_classtypeid(self._handle, pClassTypeId))
		
		return pClassTypeId.value
	


''' Class Implementation for Variable
'''
class Variable(Base):
	def __init__(self, handle, wrapper):
		Base.__init__(self, handle, wrapper)
	def GetValue(self):
		pValue = ctypes.c_double()
		self._wrapper.checkError(self, self._wrapper.lib.numbers_variable_getvalue(self._handle, pValue))
		
		return pValue.value
	
	def SetValue(self, Value):
		dValue = ctypes.c_double(Value)
		self._wrapper.checkError(self, self._wrapper.lib.numbers_variable_setvalue(self._handle, dValue))
		
	
		
