(*++

Copyright (C) 2019 Calculator developers

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.6.0-develop.

Abstract: This is an autogenerated Pascal type definition file in order to allow easy
development of Calculator library. The functions in this file need to be implemented. It needs to be generated only once.

Interface version: 1.0.0

*)

{$MODE DELPHI}
unit calculator_types;

interface

uses
  Classes,
  sysutils;

(*************************************************************************************************************************
 Version definition for Calculator
**************************************************************************************************************************)

const
  CALCULATOR_VERSION_MAJOR = 1;
  CALCULATOR_VERSION_MINOR = 0;
  CALCULATOR_VERSION_MICRO = 0;
  CALCULATOR_VERSION_PRERELEASEINFO = '';
  CALCULATOR_VERSION_BUILDINFO = '';


(*************************************************************************************************************************
 General type definitions
**************************************************************************************************************************)

type
  TCalculatorResult = Cardinal;
  TCalculatorHandle = Pointer;

  PCalculatorResult = ^TCalculatorResult;
  PCalculatorHandle = ^TCalculatorHandle;

(*************************************************************************************************************************
 Error Constants for Calculator
**************************************************************************************************************************)

const
  CALCULATOR_SUCCESS = 0;
  CALCULATOR_ERROR_NOTIMPLEMENTED = 1;
  CALCULATOR_ERROR_INVALIDPARAM = 2;
  CALCULATOR_ERROR_INVALIDCAST = 3;
  CALCULATOR_ERROR_BUFFERTOOSMALL = 4;
  CALCULATOR_ERROR_GENERICEXCEPTION = 5;
  CALCULATOR_ERROR_COULDNOTLOADLIBRARY = 6;
  CALCULATOR_ERROR_COULDNOTFINDLIBRARYEXPORT = 7;
  CALCULATOR_ERROR_INCOMPATIBLEBINARYVERSION = 8;


implementation

end.
