/*++

Copyright (C) 2018 Autodesk

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.1-develop.

Abstract: This is an autogenerated plain C Header file in order to allow an easy
 use of ACT UnitTest FrameWork

Interface version: 1.0.0

*/

#include "libunittest_types.h"
#include "libunittest_dynamic.h"
#ifdef _WIN32
#include <windows.h>
#else // _WIN32
#include <dlfcn.h>
#include <stdlib.h>
#endif // _WIN32

LibUnitTestResult InitLibUnitTestWrapperTable(sLibUnitTestDynamicWrapperTable * pWrapperTable)
{
    if (pWrapperTable == NULL)
        return LIBUNITTEST_ERROR_INVALIDPARAM;
    
    pWrapperTable->m_LibraryHandle = NULL;
    pWrapperTable->m_Base_ClassTypeId = NULL;
    pWrapperTable->m_TestClass_Value = NULL;
    pWrapperTable->m_TestClass_SetValue = NULL;
    pWrapperTable->m_TestClass_SetValueInt = NULL;
    pWrapperTable->m_TestClass_SetValueString = NULL;
    pWrapperTable->m_TestClass_UnitTest1 = NULL;
    pWrapperTable->m_TestClass_UnitTest2 = NULL;
    pWrapperTable->m_TestClass_UnitTest3 = NULL;
    pWrapperTable->m_TestClass_UnitTest4 = NULL;
    pWrapperTable->m_GetVersion = NULL;
    pWrapperTable->m_GetLastError = NULL;
    pWrapperTable->m_ReleaseInstance = NULL;
    pWrapperTable->m_AcquireInstance = NULL;
    pWrapperTable->m_InjectComponent = NULL;
    pWrapperTable->m_GetSymbolLookupMethod = NULL;
    pWrapperTable->m_CreateTestClasss = NULL;
    
    return LIBUNITTEST_SUCCESS;
}

LibUnitTestResult ReleaseLibUnitTestWrapperTable(sLibUnitTestDynamicWrapperTable * pWrapperTable)
{
    if (pWrapperTable == NULL)
        return LIBUNITTEST_ERROR_INVALIDPARAM;
    
    if (pWrapperTable->m_LibraryHandle != NULL) {
    #ifdef _WIN32
        HMODULE hModule = (HMODULE) pWrapperTable->m_LibraryHandle;
        FreeLibrary(hModule);
    #else // _WIN32
        dlclose(pWrapperTable->m_LibraryHandle);
    #endif // _WIN32
        return InitLibUnitTestWrapperTable(pWrapperTable);
    }
    
    return LIBUNITTEST_SUCCESS;
}

LibUnitTestResult LoadLibUnitTestWrapperTable(sLibUnitTestDynamicWrapperTable * pWrapperTable, const char * pLibraryFileName)
{
    if (pWrapperTable == NULL)
        return LIBUNITTEST_ERROR_INVALIDPARAM;
    if (pLibraryFileName == NULL)
        return LIBUNITTEST_ERROR_INVALIDPARAM;
    
    #ifdef _WIN32
    // Convert filename to UTF16-string
    int nLength = 0;
    while ((pLibraryFileName[nLength] != 0) && (nLength < MAX_PATH))
        nLength++;
    int nBufferSize = nLength * 2 + 2;
    wchar_t* wsLibraryFileName = (wchar_t*)malloc(nBufferSize*sizeof(wchar_t));
    memset(wsLibraryFileName, 0, nBufferSize*sizeof(wchar_t));
    int nResult = MultiByteToWideChar(CP_UTF8, 0, pLibraryFileName, nLength, wsLibraryFileName, nBufferSize);
    if (nResult == 0) {
        free(wsLibraryFileName);
        return LIBUNITTEST_ERROR_COULDNOTLOADLIBRARY;
    }
    
    HMODULE hLibrary = LoadLibraryW(wsLibraryFileName);
    free(wsLibraryFileName);
    if (hLibrary == 0) 
        return LIBUNITTEST_ERROR_COULDNOTLOADLIBRARY;
    #else // _WIN32
    void* hLibrary = dlopen(pLibraryFileName, RTLD_LAZY);
    if (hLibrary == 0) 
        return LIBUNITTEST_ERROR_COULDNOTLOADLIBRARY;
    dlerror();
    #endif // _WIN32
    
    #ifdef _WIN32
    pWrapperTable->m_Base_ClassTypeId = (PLibUnitTestBase_ClassTypeIdPtr) GetProcAddress(hLibrary, "libunittest_base_classtypeid");
    #else // _WIN32
    pWrapperTable->m_Base_ClassTypeId = (PLibUnitTestBase_ClassTypeIdPtr) dlsym(hLibrary, "libunittest_base_classtypeid");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_Base_ClassTypeId == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_TestClass_Value = (PLibUnitTestTestClass_ValuePtr) GetProcAddress(hLibrary, "libunittest_testclass_value");
    #else // _WIN32
    pWrapperTable->m_TestClass_Value = (PLibUnitTestTestClass_ValuePtr) dlsym(hLibrary, "libunittest_testclass_value");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_TestClass_Value == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_TestClass_SetValue = (PLibUnitTestTestClass_SetValuePtr) GetProcAddress(hLibrary, "libunittest_testclass_setvalue");
    #else // _WIN32
    pWrapperTable->m_TestClass_SetValue = (PLibUnitTestTestClass_SetValuePtr) dlsym(hLibrary, "libunittest_testclass_setvalue");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_TestClass_SetValue == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_TestClass_SetValueInt = (PLibUnitTestTestClass_SetValueIntPtr) GetProcAddress(hLibrary, "libunittest_testclass_setvalueint");
    #else // _WIN32
    pWrapperTable->m_TestClass_SetValueInt = (PLibUnitTestTestClass_SetValueIntPtr) dlsym(hLibrary, "libunittest_testclass_setvalueint");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_TestClass_SetValueInt == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_TestClass_SetValueString = (PLibUnitTestTestClass_SetValueStringPtr) GetProcAddress(hLibrary, "libunittest_testclass_setvaluestring");
    #else // _WIN32
    pWrapperTable->m_TestClass_SetValueString = (PLibUnitTestTestClass_SetValueStringPtr) dlsym(hLibrary, "libunittest_testclass_setvaluestring");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_TestClass_SetValueString == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_TestClass_UnitTest1 = (PLibUnitTestTestClass_UnitTest1Ptr) GetProcAddress(hLibrary, "libunittest_testclass_unittest1");
    #else // _WIN32
    pWrapperTable->m_TestClass_UnitTest1 = (PLibUnitTestTestClass_UnitTest1Ptr) dlsym(hLibrary, "libunittest_testclass_unittest1");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_TestClass_UnitTest1 == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_TestClass_UnitTest2 = (PLibUnitTestTestClass_UnitTest2Ptr) GetProcAddress(hLibrary, "libunittest_testclass_unittest2");
    #else // _WIN32
    pWrapperTable->m_TestClass_UnitTest2 = (PLibUnitTestTestClass_UnitTest2Ptr) dlsym(hLibrary, "libunittest_testclass_unittest2");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_TestClass_UnitTest2 == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_TestClass_UnitTest3 = (PLibUnitTestTestClass_UnitTest3Ptr) GetProcAddress(hLibrary, "libunittest_testclass_unittest3");
    #else // _WIN32
    pWrapperTable->m_TestClass_UnitTest3 = (PLibUnitTestTestClass_UnitTest3Ptr) dlsym(hLibrary, "libunittest_testclass_unittest3");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_TestClass_UnitTest3 == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_TestClass_UnitTest4 = (PLibUnitTestTestClass_UnitTest4Ptr) GetProcAddress(hLibrary, "libunittest_testclass_unittest4");
    #else // _WIN32
    pWrapperTable->m_TestClass_UnitTest4 = (PLibUnitTestTestClass_UnitTest4Ptr) dlsym(hLibrary, "libunittest_testclass_unittest4");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_TestClass_UnitTest4 == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_GetVersion = (PLibUnitTestGetVersionPtr) GetProcAddress(hLibrary, "libunittest_getversion");
    #else // _WIN32
    pWrapperTable->m_GetVersion = (PLibUnitTestGetVersionPtr) dlsym(hLibrary, "libunittest_getversion");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_GetVersion == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_GetLastError = (PLibUnitTestGetLastErrorPtr) GetProcAddress(hLibrary, "libunittest_getlasterror");
    #else // _WIN32
    pWrapperTable->m_GetLastError = (PLibUnitTestGetLastErrorPtr) dlsym(hLibrary, "libunittest_getlasterror");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_GetLastError == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_ReleaseInstance = (PLibUnitTestReleaseInstancePtr) GetProcAddress(hLibrary, "libunittest_releaseinstance");
    #else // _WIN32
    pWrapperTable->m_ReleaseInstance = (PLibUnitTestReleaseInstancePtr) dlsym(hLibrary, "libunittest_releaseinstance");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_ReleaseInstance == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_AcquireInstance = (PLibUnitTestAcquireInstancePtr) GetProcAddress(hLibrary, "libunittest_acquireinstance");
    #else // _WIN32
    pWrapperTable->m_AcquireInstance = (PLibUnitTestAcquireInstancePtr) dlsym(hLibrary, "libunittest_acquireinstance");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_AcquireInstance == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_InjectComponent = (PLibUnitTestInjectComponentPtr) GetProcAddress(hLibrary, "libunittest_injectcomponent");
    #else // _WIN32
    pWrapperTable->m_InjectComponent = (PLibUnitTestInjectComponentPtr) dlsym(hLibrary, "libunittest_injectcomponent");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_InjectComponent == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_GetSymbolLookupMethod = (PLibUnitTestGetSymbolLookupMethodPtr) GetProcAddress(hLibrary, "libunittest_getsymbollookupmethod");
    #else // _WIN32
    pWrapperTable->m_GetSymbolLookupMethod = (PLibUnitTestGetSymbolLookupMethodPtr) dlsym(hLibrary, "libunittest_getsymbollookupmethod");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_GetSymbolLookupMethod == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    #ifdef _WIN32
    pWrapperTable->m_CreateTestClasss = (PLibUnitTestCreateTestClasssPtr) GetProcAddress(hLibrary, "libunittest_createtestclasss");
    #else // _WIN32
    pWrapperTable->m_CreateTestClasss = (PLibUnitTestCreateTestClasssPtr) dlsym(hLibrary, "libunittest_createtestclasss");
    dlerror();
    #endif // _WIN32
    if (pWrapperTable->m_CreateTestClasss == NULL)
        return LIBUNITTEST_ERROR_COULDNOTFINDLIBRARYEXPORT;
    
    pWrapperTable->m_LibraryHandle = hLibrary;
    return LIBUNITTEST_SUCCESS;
}

LibUnitTestHandle loadLibUnitTestLibrary (const char * pFileName)
{
    LibUnitTestResult nResult;
    sLibUnitTestDynamicWrapperTable * pWrapperTable = (sLibUnitTestDynamicWrapperTable *) malloc (sizeof (sLibUnitTestDynamicWrapperTable));
    if (pWrapperTable != NULL) {
        nResult = InitLibUnitTestWrapperTable (pWrapperTable);
        if (nResult != LIBUNITTEST_SUCCESS) {
            free (pWrapperTable);
            return 0;
        }

        nResult = LoadLibUnitTestWrapperTable (pWrapperTable, pFileName);
        if (nResult != LIBUNITTEST_SUCCESS) {
            free (pWrapperTable);
            return 0;
        }

        return (LibUnitTestHandle) pWrapperTable;
    }
}

void unloadLibUnitTestLibrary (LibUnitTestHandle nLibraryHandle)
{
    sLibUnitTestDynamicWrapperTable * pWrapperTable = (sLibUnitTestDynamicWrapperTable *) malloc (sizeof (sLibUnitTestDynamicWrapperTable));
    if (pWrapperTable != NULL) {
        ReleaseLibUnitTestWrapperTable (pWrapperTable);
        free (pWrapperTable);
    }
}


LibUnitTestResult CCall_libunittest_base_classtypeid(LibUnitTestHandle libraryHandle, LibUnitTest_Base pBase, LibUnitTest_uint64 * pClassTypeId)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_Base_ClassTypeId (pBase, pClassTypeId);
}


LibUnitTestResult CCall_libunittest_testclass_value(LibUnitTestHandle libraryHandle, LibUnitTest_TestClass pTestClass, LibUnitTest_double * pValue)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_TestClass_Value (pTestClass, pValue);
}


LibUnitTestResult CCall_libunittest_testclass_setvalue(LibUnitTestHandle libraryHandle, LibUnitTest_TestClass pTestClass, LibUnitTest_double dValue)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_TestClass_SetValue (pTestClass, dValue);
}


LibUnitTestResult CCall_libunittest_testclass_setvalueint(LibUnitTestHandle libraryHandle, LibUnitTest_TestClass pTestClass, LibUnitTest_int64 nValue)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_TestClass_SetValueInt (pTestClass, nValue);
}


LibUnitTestResult CCall_libunittest_testclass_setvaluestring(LibUnitTestHandle libraryHandle, LibUnitTest_TestClass pTestClass, const char * pValue)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_TestClass_SetValueString (pTestClass, pValue);
}


LibUnitTestResult CCall_libunittest_testclass_unittest1(LibUnitTestHandle libraryHandle, LibUnitTest_TestClass pTestClass, LibUnitTest_uint8 nValue1, LibUnitTest_uint16 nValue2, LibUnitTest_uint32 nValue3, LibUnitTest_uint64 nValue4, LibUnitTest_uint8 * pOutValue1, LibUnitTest_uint16 * pOutValue2, LibUnitTest_uint32 * pOutValue3, LibUnitTest_uint64 * pOutValue4)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_TestClass_UnitTest1 (pTestClass, nValue1, nValue2, nValue3, nValue4, pOutValue1, pOutValue2, pOutValue3, pOutValue4);
}


LibUnitTestResult CCall_libunittest_testclass_unittest2(LibUnitTestHandle libraryHandle, LibUnitTest_TestClass pTestClass, LibUnitTest_int8 nValue1, LibUnitTest_int16 nValue2, LibUnitTest_int32 nValue3, LibUnitTest_int64 nValue4, LibUnitTest_int8 * pOutValue1, LibUnitTest_int16 * pOutValue2, LibUnitTest_int32 * pOutValue3, LibUnitTest_int64 * pOutValue4)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_TestClass_UnitTest2 (pTestClass, nValue1, nValue2, nValue3, nValue4, pOutValue1, pOutValue2, pOutValue3, pOutValue4);
}


LibUnitTestResult CCall_libunittest_testclass_unittest3(LibUnitTestHandle libraryHandle, LibUnitTest_TestClass pTestClass, bool bValue1, LibUnitTest_single fValue2, LibUnitTest_double dValue3, eLibUnitTestTestEnum eValue4, bool * pOutValue1, LibUnitTest_single * pOutValue2, LibUnitTest_double * pOutValue3, eLibUnitTestTestEnum * pOutValue4)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_TestClass_UnitTest3 (pTestClass, bValue1, fValue2, dValue3, eValue4, pOutValue1, pOutValue2, pOutValue3, pOutValue4);
}


LibUnitTestResult CCall_libunittest_testclass_unittest4(LibUnitTestHandle libraryHandle, LibUnitTest_TestClass pTestClass, const char * pValue, const LibUnitTest_uint32 nOutValueBufferSize, LibUnitTest_uint32* pOutValueNeededChars, char * pOutValueBuffer, const LibUnitTest_uint32 nReturnValueBufferSize, LibUnitTest_uint32* pReturnValueNeededChars, char * pReturnValueBuffer)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_TestClass_UnitTest4 (pTestClass, pValue, nOutValueBufferSize, pOutValueNeededChars, pOutValueBuffer, nReturnValueBufferSize, pReturnValueNeededChars, pReturnValueBuffer);
}


LibUnitTestResult CCall_libunittest_getversion(LibUnitTestHandle libraryHandle, LibUnitTest_uint32 * pMajor, LibUnitTest_uint32 * pMinor, LibUnitTest_uint32 * pMicro)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_GetVersion (pMajor, pMinor, pMicro);
}


LibUnitTestResult CCall_libunittest_getlasterror(LibUnitTestHandle libraryHandle, LibUnitTest_Base pInstance, const LibUnitTest_uint32 nErrorMessageBufferSize, LibUnitTest_uint32* pErrorMessageNeededChars, char * pErrorMessageBuffer, bool * pHasError)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_GetLastError (pInstance, nErrorMessageBufferSize, pErrorMessageNeededChars, pErrorMessageBuffer, pHasError);
}


LibUnitTestResult CCall_libunittest_releaseinstance(LibUnitTestHandle libraryHandle, LibUnitTest_Base pInstance)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_ReleaseInstance (pInstance);
}


LibUnitTestResult CCall_libunittest_acquireinstance(LibUnitTestHandle libraryHandle, LibUnitTest_Base pInstance)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_AcquireInstance (pInstance);
}


LibUnitTestResult CCall_libunittest_injectcomponent(LibUnitTestHandle libraryHandle, const char * pNameSpace, LibUnitTest_pvoid pSymbolAddressMethod)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_InjectComponent (pNameSpace, pSymbolAddressMethod);
}


LibUnitTestResult CCall_libunittest_getsymbollookupmethod(LibUnitTestHandle libraryHandle, LibUnitTest_pvoid * pSymbolLookupMethod)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_GetSymbolLookupMethod (pSymbolLookupMethod);
}


LibUnitTestResult CCall_libunittest_createtestclasss(LibUnitTestHandle libraryHandle, LibUnitTest_TestClass * pInstance)
{
    if (libraryHandle == 0) 
        return LIBUNITTEST_ERROR_INVALIDCAST;
    sLibUnitTestDynamicWrapperTable * wrapperTable = (sLibUnitTestDynamicWrapperTable *) libraryHandle;
    return wrapperTable->m_CreateTestClasss (pInstance);
}

