(*++

Copyright (C) 2018 PrimeDevelopers

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.4.0.

Abstract: This is an autogenerated Pascal type definition file in order to allow easy
development of Prime Numbers Library. The functions in this file need to be implemented. It needs to be generated only once.

Interface version: 1.2.0

*)

{$MODE DELPHI}
unit libprimes_types;

interface

uses
	Classes,
	sysutils;

(*************************************************************************************************************************
 Version definition for LibPrimes
**************************************************************************************************************************)

const
	LIBPRIMES_VERSION_MAJOR = 1;
	LIBPRIMES_VERSION_MINOR = 2;
	LIBPRIMES_VERSION_MICRO = 0;


(*************************************************************************************************************************
 General type definitions
**************************************************************************************************************************)

type
	TLibPrimesResult = Cardinal;
	TLibPrimesHandle = Pointer;

	PLibPrimesResult = ^TLibPrimesResult;
	PLibPrimesHandle = ^TLibPrimesHandle;

(*************************************************************************************************************************
 Error Constants for LibPrimes
**************************************************************************************************************************)

const
	LIBPRIMES_SUCCESS = 0;
	LIBPRIMES_ERROR_NOTIMPLEMENTED = 1;
	LIBPRIMES_ERROR_INVALIDPARAM = 2;
	LIBPRIMES_ERROR_INVALIDCAST = 3;
	LIBPRIMES_ERROR_BUFFERTOOSMALL = 4;
	LIBPRIMES_ERROR_GENERICEXCEPTION = 5;
	LIBPRIMES_ERROR_COULDNOTLOADLIBRARY = 6;
	LIBPRIMES_ERROR_COULDNOTFINDLIBRARYEXPORT = 7;
	LIBPRIMES_ERROR_INCOMPATIBLEBINARYVERSION = 8;
	LIBPRIMES_ERROR_NORESULTAVAILABLE = 9;
	LIBPRIMES_ERROR_CALCULATIONABORTED = 10;

(*************************************************************************************************************************
 Declaration of structs
**************************************************************************************************************************)

type

	PLibPrimesPrimeFactor = ^TLibPrimesPrimeFactor;
	TLibPrimesPrimeFactor = packed record
		FPrime: QWord;
		FMultiplicity: Cardinal;
	end;


(*************************************************************************************************************************
 Declaration of struct arrays
**************************************************************************************************************************)

	ArrayOfLibPrimesPrimeFactor = array of TLibPrimesPrimeFactor;

(*************************************************************************************************************************
 Declaration of function types
**************************************************************************************************************************)

type

	PLibPrimes_ProgressCallback = function(const fProgressPercentage: Single; out pShouldAbort: Byte): Integer; cdecl;

implementation

end.
