(*++

Copyright (C) 2019 PrimeDevelopers

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.0-develop.

Abstract: This is an autogenerated Pascal interface definition file in order to allow easy
development of Prime Numbers Library. The functions in this file need to be implemented. It needs to be generated only once.

Interface version: 1.2.0

*)

{$MODE DELPHI}
{$INTERFACES CORBA}
unit libprimes_interfaces;

interface

uses
  libprimes_types,
  Classes,
  sysutils;


type

(*************************************************************************************************************************
 Interface definition for Base
**************************************************************************************************************************)

ILibPrimesBase = interface
  ['{3C9FF988-D70B-4F52-93A8-3B8F1210321B}']

  function GetLastErrorMessage(out AErrorMessage: String): Boolean;
  procedure ClearErrorMessages();
  procedure RegisterErrorMessage(const AErrorMessage: String);
  procedure IncRefCount();
  function DecRefCount(): Boolean;
  function ClassTypeId(): QWord;
end;


(*************************************************************************************************************************
 Interface definition for Calculator
**************************************************************************************************************************)

ILibPrimesCalculator = interface(ILibPrimesBase)
  ['{BD3DF00D-EA3A-4D83-A64E-95CAC6C9F199}']

  function GetValue(): QWord;
  procedure SetValue(const AValue: QWord);
  procedure Calculate();
  procedure SetProgressCallback(const AProgressCallback: PLibPrimes_ProgressCallback);
end;


(*************************************************************************************************************************
 Interface definition for FactorizationCalculator
**************************************************************************************************************************)

ILibPrimesFactorizationCalculator = interface(ILibPrimesCalculator)
  ['{D537DB10-88AB-445E-8508-C044B94C483A}']

  procedure GetPrimeFactors(const APrimeFactorsCount: QWord; PPrimeFactorsNeededCount: PQWord; APrimeFactors: PLibPrimesPrimeFactor);
end;


(*************************************************************************************************************************
 Interface definition for SieveCalculator
**************************************************************************************************************************)

ILibPrimesSieveCalculator = interface(ILibPrimesCalculator)
  ['{017A43EA-8274-4102-B756-4AD238F14B40}']

  procedure GetPrimes(const APrimesCount: QWord; PPrimesNeededCount: PQWord; APrimes: PQWord);
end;

implementation

end.
